# Global
site_url: http://localhost:8000
site_title: My awesome website
theme: striped

# Urls
post_url: '{year}/{month}/{day}/{slug}'
page_url: '{slug}'
category_url: 'categories/{category}'
tag_url: 'tags/{tag}'
author_url: 'authors/{author}'

# Authors
authors:
    radric:
        name: Radric
        email: about@radric.io
        web: http://radric.io